// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v4"

	mock "github.com/stretchr/testify/mock"
)

// JwtGenerator is an autogenerated mock type for the JwtGenerator type
type JwtGenerator struct {
	mock.Mock
}

// GenerateContent provides a mock function with given fields: sub
func (_m *JwtGenerator) GenerateContent(sub string) jwt.MapClaims {
	ret := _m.Called(sub)

	if len(ret) == 0 {
		panic("no return value specified for GenerateContent")
	}

	var r0 jwt.MapClaims
	if rf, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = rf(sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	return r0
}

// GenerateToken provides a mock function with given fields: jwtContent
func (_m *JwtGenerator) GenerateToken(jwtContent jwt.MapClaims) (string, error) {
	ret := _m.Called(jwtContent)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.MapClaims) (string, error)); ok {
		return rf(jwtContent)
	}
	if rf, ok := ret.Get(0).(func(jwt.MapClaims) string); ok {
		r0 = rf(jwtContent)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.MapClaims) error); ok {
		r1 = rf(jwtContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJwtGenerator creates a new instance of JwtGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtGenerator {
	mock := &JwtGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
