// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/vincent-tien/bookmark-management/internal/dto"
)

// UrlShorten is an autogenerated mock type for the UrlShorten type
type UrlShorten struct {
	mock.Mock
}

// Shorten provides a mock function with given fields: ctx, r
func (_m *UrlShorten) Shorten(ctx context.Context, r dto.LinkShortenRequestDto) (string, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LinkShortenRequestDto) (string, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LinkShortenRequestDto) string); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LinkShortenRequestDto) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUrlShorten creates a new instance of UrlShorten. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlShorten(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlShorten {
	mock := &UrlShorten{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
