// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/vincent-tien/bookmark-management/internal/dto"

	model "github.com/vincent-tien/bookmark-management/internal/model"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// GetProfile provides a mock function with given fields: ctx, userId
func (_m *User) GetProfile(ctx context.Context, userId string) (*model.User, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, r
func (_m *User) Login(ctx context.Context, r dto.LoginRequestDto) (string, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequestDto) (string, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequestDto) string); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginRequestDto) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, r
func (_m *User) Register(ctx context.Context, r dto.RegisterRequestDto) (dto.RegisterResponseDto, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 dto.RegisterResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequestDto) (dto.RegisterResponseDto, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequestDto) dto.RegisterResponseDto); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(dto.RegisterResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterRequestDto) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, requestDto
func (_m *User) UpdateProfile(ctx context.Context, requestDto dto.UpdateUserProfileRequestDto) error {
	ret := _m.Called(ctx, requestDto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateUserProfileRequestDto) error); ok {
		r0 = rf(ctx, requestDto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
