// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/vincent-tien/bookmark-management/internal/dto"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// Register provides a mock function with given fields: ctx, r
func (_m *User) Register(ctx context.Context, r dto.RegisterRequestDto) (dto.RegisterResponseDto, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 dto.RegisterResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequestDto) (dto.RegisterResponseDto, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequestDto) dto.RegisterResponseDto); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(dto.RegisterResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterRequestDto) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
